// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for GalleryImage documents */
interface GalleryimageDocumentData {
    /**
     * galleryimage field in *GalleryImage*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: galleryimage.galleryimage
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    galleryimage: prismicT.ImageField<never>;
    /**
     * Slice Zone field in *GalleryImage*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: galleryimage.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<GalleryimageDocumentDataSlicesSlice>;
}
/**
 * Slice for *GalleryImage → Slice Zone*
 *
 */
type GalleryimageDocumentDataSlicesSlice = ImageBlockSlice;
/**
 * GalleryImage document from Prismic
 *
 * - **API ID**: `galleryimage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryimageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<GalleryimageDocumentData>, "galleryimage", Lang>;
export type AllDocumentTypes = GalleryimageDocument;
/**
 * Primary content in ImageBlock → Primary
 *
 */
interface ImageBlockSliceDefaultPrimary {
    /**
     * Title field in *ImageBlock → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: image_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
    /**
     * Description field in *ImageBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: image_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Item in ImageBlock → Items
 *
 */
export interface ImageBlockSliceDefaultItem {
    /**
     * galleryslice field in *ImageBlock → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image_block.items[].galleryslice
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    galleryslice: prismicT.ImageField<never>;
}
/**
 * Default variation for ImageBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ImageBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageBlockSliceDefaultPrimary>, Simplify<ImageBlockSliceDefaultItem>>;
/**
 * Slice variation for *ImageBlock*
 *
 */
type ImageBlockSliceVariation = ImageBlockSliceDefault;
/**
 * ImageBlock Shared Slice
 *
 * - **API ID**: `image_block`
 * - **Description**: `ImageBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageBlockSlice = prismicT.SharedSlice<"image_block", ImageBlockSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { GalleryimageDocumentData, GalleryimageDocumentDataSlicesSlice, GalleryimageDocument, AllDocumentTypes, ImageBlockSliceDefaultPrimary, ImageBlockSliceDefaultItem, ImageBlockSliceDefault, ImageBlockSliceVariation, ImageBlockSlice };
    }
}
