const configurationConstants = {
  CAMERA_FOV: 50,
  CAMERA_NEAR: 0.1,
  CAMERA_FAR: 2000,

  LIGHT_COLOR: 0xffffff,
  LIGHT_INTENSITY: 1,
  LIGHT_DISTANCE: 100,

  LIGHT_TWO_COLOR: 0xffffff,
  LIGHT_TWO_INTENSITY: 1,
  LIGHT_TWO_DISTANCE: 100,

  LIGHT_THREE_COLOR: 0xffffff,
  LIGHT_THREE_INTENSITY: 1,
  LIGHT_THREE_DISTANCE: 100,

  LIGHT_FOUR_COLOR: 0xffffff,
  LIGHT_FOUR_INTENSITY: 1,
  LIGHT_FOUR_DISTANCE: 100,

  LIGHT_FIVE_COLOR: 0xffffff,
  LIGHT_FIVE_INTENSITY: 1,
  LIGHT_FIVE_DISTANCE: 100,

  LIGHT_SIX_COLOR: 0xffffff,
  LIGHT_SIX_INTENSITY: 1,
  LIGHT_SIX_DISTANCE: 100,

  YOUR_MAX_ZOOM: 100,
  YOUR_MIN_ZOOM: 10,
};

export default configurationConstants;
